import 'package:flutter/material.dart';

class AppLang {
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'version': 'GEAR UP Version 2.0.0',
      'copyright': '© 2026 GEAR UP. All rights reserved.',
      // ================= Start Selling =================
      'start_selling_title': 'Start Selling',
      'choose_item_type': 'Choose item type and add details',
      'change': 'Change',
      'photos': 'Photos',
      'add_photo': 'Add Photo',
      'photo_hint': '0/10 photos - Add clear photos from different angles',
      'title': 'Title',
      'title_hint': 'Enter an attractive title',
      'price_egp': 'Price (EGP)',
      'price_hint': 'Enter price',
      'transmission_hint': 'Select type',
      'part_name': 'Part/Accessory Name',
      'part_hint': 'e.g., Ceramic Brake Pads',
      'compatibility': 'Compatibility',
      'compat_hint': 'e.g., BMW X5 2020-2024',
      'condition': 'Condition',
      'condition_hint': 'Select condition',
      'description': 'Description',
      'desc_hint': 'Add a detailed description...',
      'publish_listing': 'Publish Listing',
      'select_item_type': 'Select Item Type',
      'type_car': 'Car',
      'type_part': 'Car Part',
      'type_accessory': 'Accessory',
      'automatic': 'Automatic',
      'manual': 'Manual',
      'new_condition': 'New',
      'used_condition': 'Used',
      'refurbished': 'Refurbished',
      // ================= Privacy Policy =================
      'privacy_policy_title': 'Privacy Policy',
      'last_updated': 'Last updated: October 23, 2025',
      'pp_sec1_title': '1. Information We Collect',
      'pp_sec1_p1': 'GEAR UP collects information that you provide directly to us when you create an account, use our services, or communicate with us. This may include your name, email address, phone number, and vehicle information.',
      'pp_sec1_p2': 'We also automatically collect certain information about your device and how you interact with our app, including your IP address, device type, operating system, and usage patterns.',
      'pp_sec2_title': '2. How We Use Your Information',
      'pp_sec2_p1': 'We use the information we collect to:',
      'pp_sec2_b1': 'Provide, maintain, and improve our services',
      'pp_sec2_b2': 'Send you technical notices and support messages',
      'pp_sec2_b3': 'Respond to your comments and questions',
      'pp_sec2_b4': 'Provide personalized car recommendations',
      'pp_sec2_b5': 'Monitor and analyze trends, usage, and activities',
      'pp_sec2_b6': 'Detect, prevent, and address technical issues',
      'pp_sec3_title': '3. Information Sharing',
      'pp_sec3_p1': 'We do not sell your personal information. We may share your information only in the following circumstances: with your consent, with service providers who help us operate our business, to comply with legal obligations, or to protect our rights and safety.',
      'pp_sec4_title': '4. Data Security',
      'pp_sec4_p1': 'We take reasonable measures to help protect your personal information from loss, theft, misuse, unauthorized access, disclosure, alteration, and destruction. However, no internet transmission is ever fully secure or error-free.',
      'pp_sec5_title': '5. Your Rights and Choices',
      'pp_sec5_p1': 'You have the right to:',
      'pp_sec5_b1': 'Access and update your account information',
      'pp_sec5_b2': 'Request deletion of your personal data',
      'pp_sec5_b3': 'Opt-out of marketing communications',
      'pp_sec5_b4': 'Disable cookies through your browser settings',
      'pp_sec6_title': '6. Children\'s Privacy',
      'pp_sec6_p1': 'Our services are not directed to children under 13. We do not knowingly collect personal information from children under 13. If you become aware that a child has provided us with personal information, please contact us.',
      'pp_sec7_title': '7. Changes to This Policy',
      'pp_sec7_p1': 'We may update this privacy policy from time to time. We will notify you of any changes by posting the new privacy policy on this page and updating the "Last updated" date.',
      'pp_sec8_title': '8. Contact Us',
      'pp_sec8_p1': 'If you have any questions about this Privacy Policy, please contact us at:\nEmail: privacy@gearup.com\nPhone: +20 2 1234 5678',

// ================= Profile Screen =================
      'my_account': 'My Account',
      'start_selling': 'Start Selling',
      'list_new_item': 'List a new item',
      'published_items': 'Published Items',
      'manage_listings': 'Manage your listings',
      'account_info_sub': 'Name, email, phone',
      'edit_profile_sub': 'Update your information',
      'manage_payment_methods': 'Manage Payment Methods',
      'app_section': 'App',
      'settings_sub': 'Preferences, Privacy, Help',
      'logout': 'Logout',
      'egypt_car_app': 'Egypt\'s #1 Car App',

// ================= Published Items =================
      'tab_all': 'All',
      'tab_cars': 'Cars',
      'tab_parts': 'Parts',
      'tab_accessories': 'Accessories',
      'no_listings_yet': 'No listings yet',
      'haven_not_published': 'You haven\'t published any listings yet',
      // ================= Profile & Account =================
      'account_information': 'Account Information',
      'view_account_details': 'View your account details',
      'member_since': 'Member Since',
      'email_address': 'Email Address',
      'location': 'Location',
      'edit_information': 'Edit Information',
      'update_account_password': 'Update your account password',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'update_password': 'Update Password', // تم توحيد هذا المفتاح وحذف المكرر
      'edit_profile': 'Edit Profile',
      'change_profile_photo': 'Change Profile Photo',

      // ================= Nearby Locations =================
      'nearby_locations': 'Nearby Locations',
      'service_and_showrooms': 'Service centers & showrooms',
      'interactive_map': 'Interactive Map',
      'shows_places_near_you': 'Shows service centers & showrooms near you',
      'service_center': 'Service Center',
      'showroom': 'Showroom',
      'km_away': 'km away',
      'get_directions': 'Get Directions',

      // ================= Parts Screen =================
      'car_parts': 'Car Parts',
      'parts_available': 'parts available',
      'search_parts': 'Search parts...',
      'all_companies': 'All Companies',
      'default_sort': 'Default',
      'fits': 'Fits: ',

      // ================= General & Navigation =================
      'home': 'Home',
      'compare': 'Compare',
      'parts': 'Parts',
      'my_car': 'My Car',
      'profile': 'Profile',
      'settings': 'Settings',
      'cancel': 'Cancel',
      'save_changes': 'Save Changes',
      'delete': 'Delete',
      'remove': 'Remove',
      'submit': 'Submit',
      'view_more': 'View More',
      'manage': 'Manage',

      // ================= Splash & Welcome =================
      'premium_companion': 'Your Premium Car Companion',
      'skip_to_home': 'Skip to Home',

      // ================= Auth Screens =================
      'welcome_back': 'Welcome Back',
      'sign_in': 'Sign in to continue',
      'login': 'Login',
      'forgot_password_title': 'Forgot Password?',
      'forgot_password_desc': 'Enter your email and we\'ll send you instructions to reset your password',
      'email': 'Email',
      'email_hint': 'your@email.com',
      'send_reset_link': 'Send Reset Link',
      'back_to_login': 'Back to Login',
      'password': 'Password',
      'password_hint': '••••••••',
      'or_continue_with': 'Or continue with',
      'google': 'Google',
      'facebook': 'Facebook',
      'dont_have_account': 'Don\'t have an account? ',
      'sign_up': 'Sign up',
      'create_account': 'Create Account',
      'join_gear_up': 'Join GEAR UP today',
      'full_name': 'Full Name',
      'full_name_hint': 'Your full name',
      'phone_number': 'Phone Number',
      'phone_hint': '+20 123 456 7890',
      'confirm_password': 'Confirm Password',
      'already_have_account': 'Already have an account? ',

      // ================= Home & Search =================
      'popular_searches': 'POPULAR SEARCHES',
      'saved_cars': 'Saved Cars',
      'saved_parts': 'Saved Parts',
      'find_nearby': 'Find Nearby',
      'promoted': 'Promoted',
      'featured_listings': 'Featured Listings',
      'premium_listings': 'Premium featured listings',
      'top_rated_new': 'Top Rated New Cars',
      'best_rated_2025': 'Best rated vehicles in 2025',
      'news_insights': 'News & Insights',
      'latest_updates': 'Latest automotive updates',
      'new_cars': 'New Cars',
      'latest_models': 'Latest models from top brands',
      'used_cars': 'Used Cars',
      'quality_preowned': 'Quality pre-owned vehicles',

      // ================= Compare & Car Details =================
      'compare_vehicles': 'Compare Vehicles',
      'analyze_specs': 'Analyze side-by-side specifications',
      'specification': 'Specification',
      'company': 'Company',
      'model': 'Model',
      'year': 'Year',
      'average_price': 'Average Price',
      'transmission': 'Transmission',
      'mileage': 'Mileage',
      'hp': 'HP',
      'cc': 'CC',
      'torque': 'Torque',
      'luggage_capacity': 'Luggage Capacity',
      'gear_shifts': 'Gear Shifts',
      'max_speed': 'Max Speed',
      'comparison_guide': 'Comparison Guide',
      'indicates_advantage': 'Indicates advantage',
      'indicates_disadvantage': 'Indicates disadvantage',
      'specifications_title': 'Specifications',
      'about_vehicle': 'About this vehicle',
      'added_to_comparison': 'Added to Comparison',
      'total_views': 'Total Views',
      'reviews': 'Reviews',
      'top_rated': 'Top Rated',
      'write_review': 'Write a Review',
      'share_experience': 'Share your experience with this car...',
      'mock_desc': 'is a premium vehicle featuring a powerful 335 HP engine with 3000cc capacity. With its Automatic transmission and 8 gear shifts, this car delivers exceptional performance and efficiency. The vehicle can reach a maximum speed of 250 km/h and offers 650 L of luggage capacity, making it perfect for both daily commutes and long journeys.',

      // ================= My Car & Reminders =================
      'login_signup_msg': 'Log in or sign up to manage your vehicle, track maintenance history, and set reminders',
      'manage_vehicles': 'Manage your vehicles',
      'my_vehicle': 'My Vehicle',
      'maintenance_history': 'Maintenance History',
      'add_record': 'Add Record',
      'service_centers': 'Service Centers',
      'edit_record': 'Edit Record',
      'service_name': 'Service Name',
      'cost_egp': 'Cost (EGP)',
      'description_details': 'Description / Details',
      'parts_used_notes': 'Parts used, mechanic notes...',
      'edit_my_vehicle': 'Edit My Vehicle',
      'vehicle_details': 'Vehicle Details',
      'update_car_info': 'Update your car\'s information and mileage',
      'change_vehicle_photo': 'Change Vehicle Photo',
      'car_brand': 'Car Brand',
      'car_model': 'Car Model',
      'manufacturing_year': 'Manufacturing Year',
      'mileage_km': 'Mileage (km)',
      'upcoming_reminders': 'Upcoming Reminders',
      'manage_reminders': 'Manage your car maintenance reminders',
      'add_reminder': 'Add Reminder',
      'edit_reminder': 'Edit Reminder',
      'due_date': 'Due: ',
      'task': 'Task',
      'task_hint': 'e.g., Oil Change, Tire Rotation',
      'date_hint': 'mm/dd/yyyy',
      'notes_optional': 'Notes (Optional)',
      'additional_details': 'Additional details...',
      'delete_reminder': 'Delete Reminder',
      'delete_confirm_msg': 'Are you sure you want to delete this reminder? This action cannot be undone.',
      'reminder_deleted': 'Reminder deleted successfully!',

      // ================= AI Chat & Filters =================
      'ai_title': 'GEAR UP AI',
      'ai_subtitle': 'Always here to help',
      'ai_greeting': 'Hi! I\'m your GEAR UP AI assistant. How can I help you today?',
      'quick_suggestions': 'Quick suggestions:',
      'sugg_electric': 'Show me electric cars',
      'sugg_sedans': 'Compare sedans under 30k',
      'sugg_suvs': 'Best SUVs for families',
      'type_message': 'Type your message...',
      'filters': 'Filters',
      'price': 'Price',
      'high_to_low': 'High to Low',
      'low_to_high': 'Low to High',
      'under_500k': 'Under 500K',

      // ================= Settings Screen =================
      'manage_preferences': 'Manage your app preferences & support',
      'app_preferences': 'App Preferences',
      'dark_mode': 'Dark Mode',
      'dark_enabled': 'Dark theme enabled',
      'light_enabled': 'Light theme enabled',
      'push_notifications': 'Push Notifications',
      'receive_updates': 'Receive updates and reminders',
      'language': 'Language',
      'select_language': 'Select your preferred language',
      'security_privacy': 'Security & Privacy',
      'change_password': 'Change Password',
      'privacy_policy': 'Privacy Policy',
      'terms_privacy': 'Terms and privacy rules',
      'support_about': 'Support & About',
      'help_center': 'Help Center',
      'get_support': 'Get support & FAQ',
      'analytics': 'Analytics & Performance',
      'help_improve': 'Help improve the app',

      // ================= Help Center Screen =================
      'search_help': 'Search for help...',
      'chat_support': 'Chat Support',
      'call_us': 'Call Us',
      'email_us': 'Email Us',
      'user_guide': 'User Guide',
      'categories': 'Categories',
      'all': 'All',
      'general': 'General',
      'features': 'Features',
      'service': 'Service',
      'faq': 'Frequently Asked Questions',
      'still_need_help': 'Still need help?',
      'phone': 'Phone',
      'faq_q1': 'How do I search for a car?',
      'faq_a1': 'You can search for cars by browsing the Home screen or using the Search bar at the top.',
      'faq_q2': 'How do I save a car to my favorites?',
      'faq_a2': 'Tap the heart icon on any car card to save it to your Saved Cars list.',
      'faq_q3': 'How does the comparison feature work?',
      'faq_a3': 'Select up to 2 cars by tapping the compare icon, then go to the Compare tab to see them side-by-side.',
      'faq_q4': 'Can I track my car maintenance?',
      'faq_a4': 'Yes! Go to your Profile, then "My Car" to add and track your maintenance history.',
      'faq_q5': 'How do I find car parts?',
      'faq_a5': 'Visit the Parts tab to browse or search for specific car parts.',
      'faq_q6': 'How do I reset my password?',
      'faq_a6': 'On the login screen, tap "Forgot Password?" to receive a reset link.',
      'faq_q7': 'Where can I find service centers near me?',
      'faq_a7': 'Go to the Home screen and tap "Find Nearby" to see a map of service centers.',
      'faq_q8': 'How do I enable dark mode?',
      'faq_a8': 'Navigate to Settings from your Profile and toggle the Dark Mode switch.',
      'faq_q9': 'What is the AI Chat Agent?',
      'faq_a9': 'The AI Chat Agent is your virtual assistant. Tap the floating icon to ask questions.',
      'faq_q10': 'How do I change my profile information?',
      'faq_a10': 'Go to your Profile page and tap "Edit Information".',

      // ================= Payments Screen =================
      'payments': 'Payments',
      'manage_payments': 'Manage Payments',
      'payment_methods': 'Payment Methods',
      'history': 'History',
      'add_payment_method': 'Add Payment Method',
      'default_method': 'Default',
      'select_payment_method': 'Select Payment Method',
      'credit_debit_card': 'Credit / Debit Card',
      'add_card': 'Add Card',
      'add_instapay': 'Add InstaPay',
      'add_vodafone_cash': 'Add Vodafone Cash',
      'card_number': 'Card Number',
      'cardholder_name': 'Cardholder Name',
      'expiry_date': 'Expiry Date',
      'cvv': 'CVV',
      'name': 'Name',
      'completed': 'Completed',
      'pending': 'Pending',
    },
    'ar': {
      'version': 'تطبيق GEAR UP إصدار 2.0.0',
      'copyright': '© 2026 GEAR UP. جميع الحقوق محفوظة.',
      // ================= Start Selling =================
      'start_selling_title': 'ابدأ البيع',
      'choose_item_type': 'اختر نوع العنصر وأضف التفاصيل',
      'change': 'تغيير',
      'photos': 'الصور',
      'add_photo': 'إضافة صورة',
      'photo_hint': '0/10 صور - أضف صوراً واضحة من زوايا مختلفة',
      'title': 'العنوان',
      'title_hint': 'أدخل عنواناً جذاباً',
      'price_egp': 'السعر (ج.م)',
      'price_hint': 'أدخل السعر',
      'transmission_hint': 'اختر النوع',
      'part_name': 'اسم القطعة/الإكسسوار',
      'part_hint': 'مثال: تيل فرامل سيراميك',
      'compatibility': 'التوافق',
      'compat_hint': 'مثال: BMW X5 2020-2024',
      'condition': 'الحالة',
      'condition_hint': 'اختر الحالة',
      'description': 'الوصف',
      'desc_hint': 'أضف وصفاً تفصيلياً...',
      'publish_listing': 'نشر الإعلان',
      'select_item_type': 'اختر نوع العنصر',
      'type_car': 'سيارة',
      'type_part': 'قطعة غيار',
      'type_accessory': 'إكسسوار',
      'automatic': 'أوتوماتيك',
      'manual': 'مانيوال',
      'new_condition': 'جديد',
      'used_condition': 'مستعمل',
      'refurbished': 'مجدد',
      // ================= Privacy Policy =================
      'privacy_policy_title': 'سياسة الخصوصية',
      'last_updated': 'آخر تحديث: 23 أكتوبر 2025',
      'pp_sec1_title': '1. المعلومات التي نجمعها',
      'pp_sec1_p1': 'تقوم GEAR UP بجمع المعلومات التي تقدمها لنا مباشرة عند إنشاء حساب، أو استخدام خدماتنا، أو التواصل معنا. قد يشمل ذلك اسمك وعنوان بريدك الإلكتروني ورقم هاتفك ومعلومات سيارتك.',
      'pp_sec1_p2': 'نقوم أيضاً تلقائياً بجمع معلومات معينة حول جهازك وكيفية تفاعلك مع تطبيقنا، بما في ذلك عنوان IP الخاص بك، ونوع الجهاز، ونظام التشغيل، وأنماط الاستخدام.',
      'pp_sec2_title': '2. كيف نستخدم معلوماتك',
      'pp_sec2_p1': 'نستخدم المعلومات التي نجمعها من أجل:',
      'pp_sec2_b1': 'توفير خدماتنا وصيانتها وتحسينها',
      'pp_sec2_b2': 'إرسال إشعارات فنية ورسائل دعم',
      'pp_sec2_b3': 'الرد على تعليقاتك وأسئلتك',
      'pp_sec2_b4': 'تقديم توصيات سيارات مخصصة',
      'pp_sec2_b5': 'مراقبة وتحليل الاتجاهات والاستخدام والأنشطة',
      'pp_sec2_b6': 'اكتشاف المشكلات الفنية ومنعها ومعالجتها',
      'pp_sec3_title': '3. مشاركة المعلومات',
      'pp_sec3_p1': 'نحن لا نبيع معلوماتك الشخصية. قد نشارك معلوماتك فقط في الحالات التالية: بموافقتك، مع مقدمي الخدمات الذين يساعدوننا في إدارة أعمالنا، للامتثال للالتزامات القانونية، أو لحماية حقوقنا وسلامتنا.',
      'pp_sec4_title': '4. أمن البيانات',
      'pp_sec4_p1': 'نتخذ تدابير معقولة للمساعدة في حماية معلوماتك الشخصية من الفقدان والسرقة وسوء الاستخدام والوصول غير المصرح به والإفصاح والتعديل والإتلاف. ومع ذلك، لا يوجد نقل عبر الإنترنت آمن تماماً أو خالٍ من الأخطاء.',
      'pp_sec5_title': '5. حقوقك وخياراتك',
      'pp_sec5_p1': 'لديك الحق في:',
      'pp_sec5_b1': 'الوصول إلى معلومات حسابك وتحديثها',
      'pp_sec5_b2': 'طلب حذف بياناتك الشخصية',
      'pp_sec5_b3': 'إلغاء الاشتراك في المراسلات التسويقية',
      'pp_sec5_b4': 'تعطيل ملفات تعريف الارتباط من خلال إعدادات المتصفح',
      'pp_sec6_title': '6. خصوصية الأطفال',
      'pp_sec6_p1': 'خدماتنا غير موجهة للأطفال دون سن 13 عاماً. نحن لا نجمع عن قصد معلومات شخصية من الأطفال دون سن 13. إذا علمت أن طفلاً قد زودنا بمعلومات شخصية، يرجى الاتصال بنا.',
      'pp_sec7_title': '7. التغييرات على هذه السياسة',
      'pp_sec7_p1': 'قد نقوم بتحديث سياسة الخصوصية هذه من وقت لآخر. سنقوم بإعلامك بأي تغييرات عن طريق نشر سياسة الخصوصية الجديدة على هذه الصفحة وتحديث تاريخ "آخر تحديث".',
      'pp_sec8_title': '8. اتصل بنا',
      'pp_sec8_p1': 'إذا كان لديك أي أسئلة حول سياسة الخصوصية هذه، يرجى الاتصال بنا على:\nالبريد الإلكتروني: privacy@gearup.com\nالهاتف: +20 2 1234 5678',

// ================= Profile Screen =================
      'my_account': 'حسابي',
      'start_selling': 'ابدأ البيع',
      'list_new_item': 'عرض عنصر جديد للبيع',
      'published_items': 'العناصر المنشورة',
      'manage_listings': 'إدارة إعلاناتك',
      'account_info_sub': 'الاسم، البريد، الهاتف',
      'edit_profile_sub': 'تحديث معلوماتك',
      'manage_payment_methods': 'إدارة طرق الدفع',
      'app_section': 'التطبيق',
      'settings_sub': 'التفضيلات، الخصوصية، المساعدة',
      'logout': 'تسجيل الخروج',
      'egypt_car_app': 'تطبيق السيارات رقم 1 في مصر',

// ================= Published Items =================
      'tab_all': 'الكل',
      'tab_cars': 'سيارات',
      'tab_parts': 'قطع غيار',
      'tab_accessories': 'إكسسوارات',
      'no_listings_yet': 'لا توجد إعلانات بعد',
      'haven_not_published': 'لم تقم بنشر أي إعلانات حتى الآن',
      // ================= Profile & Account =================
      'account_information': 'معلومات الحساب',
      'view_account_details': 'عرض تفاصيل حسابك',
      'member_since': 'عضو منذ',
      'email_address': 'البريد الإلكتروني',
      'location': 'الموقع',
      'edit_information': 'تعديل المعلومات',
      'update_account_password': 'تحديث كلمة مرور حسابك',
      'current_password': 'كلمة المرور الحالية',
      'new_password': 'كلمة المرور الجديدة',
      'confirm_new_password': 'تأكيد كلمة المرور الجديدة',
      'update_password': 'تحديث كلمة المرور', // تم توحيد المفتاح
      'edit_profile': 'تعديل الملف الشخصي',
      'change_profile_photo': 'تغيير صورة الملف الشخصي',

      // ================= Nearby Locations =================
      'nearby_locations': 'الأماكن القريبة',
      'service_and_showrooms': 'مراكز صيانة ومعارض سيارات',
      'interactive_map': 'خريطة تفاعلية',
      'shows_places_near_you': 'تعرض مراكز الصيانة والمعارض القريبة منك',
      'service_center': 'مركز صيانة',
      'showroom': 'معرض سيارات',
      'km_away': 'كم',
      'get_directions': 'الحصول على الاتجاهات',

      // ================= Parts Screen =================
      'car_parts': 'قطع غيار',
      'parts_available': 'قطع متوفرة',
      'search_parts': 'ابحث عن قطع الغيار...',
      'all_companies': 'كل الشركات',
      'default_sort': 'الافتراضي',
      'fits': 'تناسب موديلات: ',

      // ================= General & Navigation =================
      'home': 'الرئيسية',
      'compare': 'مقارنة',
      'parts': 'قطع غيار',
      'my_car': 'سيارتي',
      'profile': 'حسابي',
      'settings': 'الإعدادات',
      'cancel': 'إلغاء',
      'save_changes': 'حفظ التغييرات',
      'delete': 'حذف',
      'remove': 'إزالة',
      'submit': 'إرسال',
      'view_more': 'عرض المزيد',
      'manage': 'إدارة',

      // ================= Splash & Welcome =================
      'premium_companion': 'رفيقك المتميز للسيارات',
      'skip_to_home': 'تخطي للرئيسية',

      // ================= Auth Screens =================
      'welcome_back': 'مرحباً بعودتك',
      'sign_in': 'سجل الدخول للمتابعة',
      'login': 'تسجيل الدخول',
      'forgot_password_title': 'هل نسيت كلمة المرور؟',
      'forgot_password_desc': 'أدخل بريدك الإلكتروني وسنرسل لك تعليمات لإعادة تعيين كلمة المرور',
      'email': 'البريد الإلكتروني',
      'email_hint': 'your@email.com',
      'send_reset_link': 'إرسال رابط الاستعادة',
      'back_to_login': 'الرجوع لتسجيل الدخول',
      'password': 'كلمة المرور',
      'password_hint': '••••••••',
      'or_continue_with': 'أو المتابعة باستخدام',
      'google': 'جوجل',
      'facebook': 'فيسبوك',
      'dont_have_account': 'ليس لديك حساب؟ ',
      'sign_up': 'إنشاء حساب',
      'create_account': 'إنشاء حساب جديد',
      'join_gear_up': 'انضم إلى GEAR UP اليوم',
      'full_name': 'الاسم الكامل',
      'full_name_hint': 'اكتب اسمك بالكامل',
      'phone_number': 'رقم الهاتف',
      'phone_hint': '+20 123 456 7890',
      'confirm_password': 'تأكيد كلمة المرور',
      'already_have_account': 'لديك حساب بالفعل؟ ',

      // ================= Home & Search =================
      'popular_searches': 'عمليات البحث الشائعة',
      'saved_cars': 'السيارات المحفوظة',
      'saved_parts': 'القطع المحفوظة',
      'find_nearby': 'الأماكن القريبة',
      'promoted': 'إعلانات ممولة',
      'featured_listings': 'قوائم مميزة',
      'premium_listings': 'إعلانات مميزة ومدفوعة',
      'top_rated_new': 'سيارات جديدة عالية التقييم',
      'best_rated_2025': 'أفضل السيارات تقييماً في 2025',
      'news_insights': 'الأخبار والتحليلات',
      'latest_updates': 'أحدث أخبار السيارات',
      'new_cars': 'سيارات جديدة',
      'latest_models': 'أحدث الموديلات من أشهر العلامات',
      'used_cars': 'سيارات مستعملة',
      'quality_preowned': 'سيارات مستعملة بجودة عالية',

      // ================= Compare & Car Details =================
      'compare_vehicles': 'مقارنة السيارات',
      'analyze_specs': 'تحليل المواصفات جنباً إلى جنب',
      'specification': 'المواصفة',
      'company': 'الشركة',
      'model': 'الموديل',
      'year': 'سنة الصنع',
      'average_price': 'متوسط السعر',
      'transmission': 'ناقل الحركة',
      'mileage': 'المسافة المقطوعة',
      'hp': 'قوة الحصان',
      'cc': 'سعة المحرك',
      'torque': 'عزم الدوران',
      'luggage_capacity': 'سعة الشنطة',
      'gear_shifts': 'عدد النقلات',
      'max_speed': 'السرعة القصوى',
      'comparison_guide': 'دليل المقارنة',
      'indicates_advantage': 'يشير إلى ميزة (أفضل)',
      'indicates_disadvantage': 'يشير إلى عيب (أقل)',
      'specifications_title': 'المواصفات',
      'about_vehicle': 'عن هذه السيارة',
      'added_to_comparison': 'تمت الإضافة للمقارنة',
      'total_views': 'إجمالي المشاهدات',
      'reviews': 'التقييمات',
      'top_rated': 'الأعلى تقييماً',
      'write_review': 'اكتب تقييماً',
      'share_experience': 'شارك تجربتك مع هذه السيارة...',
      'mock_desc': 'هي سيارة فاخرة تتميز بمحرك قوي بقوة 335 حصان وسعة 3000 سي سي. مع ناقل حركة أوتوماتيكي و 8 نقلات، تقدم هذه السيارة أداءً وكفاءة استثنائية. يمكن للسيارة الوصول لسرعة قصوى تبلغ 250 كم/ساعة وتوفر سعة أمتعة 650 لتر، مما يجعلها مثالية للتنقلات اليومية والرحلات الطويلة.',

      // ================= My Car & Reminders =================
      'login_signup_msg': 'سجل الدخول أو أنشئ حساباً لإدارة سيارتك، وتتبع سجل الصيانة، وتعيين التذكيرات',
      'manage_vehicles': 'إدارة سياراتك',
      'my_vehicle': 'سيارتي',
      'maintenance_history': 'سجل الصيانة',
      'add_record': 'إضافة سجل',
      'service_centers': 'مراكز الصيانة',
      'edit_record': 'تعديل السجل',
      'service_name': 'اسم الخدمة',
      'cost_egp': 'التكلفة (ج.م)',
      'description_details': 'الوصف / التفاصيل',
      'parts_used_notes': 'القطع المستخدمة، ملاحظات الميكانيكي...',
      'edit_my_vehicle': 'تعديل سيارتي',
      'vehicle_details': 'تفاصيل السيارة',
      'update_car_info': 'قم بتحديث معلومات سيارتك والمسافة المقطوعة',
      'change_vehicle_photo': 'تغيير صورة السيارة',
      'car_brand': 'ماركة السيارة',
      'car_model': 'موديل السيارة',
      'manufacturing_year': 'سنة الصنع',
      'mileage_km': 'المسافة (كم)',
      'upcoming_reminders': 'التذكيرات القادمة',
      'manage_reminders': 'إدارة تذكيرات صيانة سيارتك',
      'add_reminder': 'إضافة تذكير',
      'edit_reminder': 'تعديل التذكير',
      'due_date': 'الاستحقاق: ',
      'task': 'المهمة',
      'task_hint': 'مثال: تغيير الزيت، تدوير الإطارات',
      'date_hint': 'يوم/شهر/سنة',
      'notes_optional': 'ملاحظات (اختياري)',
      'additional_details': 'تفاصيل إضافية...',
      'delete_reminder': 'حذف التذكير',
      'delete_confirm_msg': 'هل أنت متأكد من حذف هذا التذكير؟ لا يمكن التراجع عن هذا الإجراء.',
      'reminder_deleted': 'تم حذف التذكير بنجاح!',

      // ================= AI Chat & Filters =================
      'ai_title': 'مساعد GEAR UP',
      'ai_subtitle': 'دائماً هنا للمساعدة',
      'ai_greeting': 'أهلاً بك! أنا مساعدك الذكي. كيف يمكنني مساعدتك اليوم؟',
      'quick_suggestions': 'اقتراحات سريعة:',
      'sugg_electric': 'اعرض لي السيارات الكهربائية',
      'sugg_sedans': 'قارن سيارات السيدان تحت 30 ألف',
      'sugg_suvs': 'أفضل سيارات الدفع الرباعي للعائلات',
      'type_message': 'اكتب رسالتك...',
      'filters': 'الفلاتر',
      'price': 'السعر',
      'high_to_low': 'من الأعلى للأقل',
      'low_to_high': 'من الأقل للأعلى',
      'under_500k': 'أقل من 500 ألف',

      // ================= Settings Screen =================
      'manage_preferences': 'إدارة تفضيلات التطبيق والدعم',
      'app_preferences': 'تفضيلات التطبيق',
      'dark_mode': 'الوضع الليلي',
      'dark_enabled': 'الوضع الليلي مفعل',
      'light_enabled': 'الوضع الفاتح مفعل',
      'push_notifications': 'الإشعارات',
      'receive_updates': 'استلام التحديثات والتذكيرات',
      'language': 'اللغة',
      'select_language': 'اختر لغتك المفضلة',
      'security_privacy': 'الأمان والخصوصية',
      'change_password': 'تغيير كلمة المرور',
      'privacy_policy': 'سياسة الخصوصية',
      'terms_privacy': 'الشروط وقواعد الخصوصية',
      'support_about': 'الدعم وحول التطبيق',
      'help_center': 'مركز المساعدة',
      'get_support': 'الحصول على الدعم والأسئلة الشائعة',
      'analytics': 'التحليلات والأداء',
      'help_improve': 'المساعدة في تحسين التطبيق',

      // ================= Help Center Screen =================
      'search_help': 'ابحث عن المساعدة...',
      'chat_support': 'دعم المحادثة',
      'call_us': 'اتصل بنا',
      'email_us': 'راسلنا',
      'user_guide': 'دليل المستخدم',
      'categories': 'الفئات',
      'all': 'الكل',
      'general': 'عام',
      'features': 'الميزات',
      'service': 'الصيانة',
      'faq': 'الأسئلة الشائعة',
      'still_need_help': 'هل ما زلت بحاجة للمساعدة؟',
      'phone': 'الهاتف',
      'faq_q1': 'كيف أبحث عن سيارة؟',
      'faq_a1': 'يمكنك البحث عن السيارات من خلال تصفح الشاشة الرئيسية أو استخدام شريط البحث في الأعلى.',
      'faq_q2': 'كيف أحفظ سيارة في المفضلة؟',
      'faq_a2': 'اضغط على أيقونة القلب على أي بطاقة سيارة لحفظها في قائمة السيارات المحفوظة.',
      'faq_q3': 'كيف تعمل ميزة المقارنة؟',
      'faq_a3': 'حدد سيارتين بالضغط على أيقونة المقارنة، ثم اذهب لعلامة تبويب المقارنة لرؤيتهما جنباً إلى جنب.',
      'faq_q4': 'هل يمكنني تتبع صيانة سيارتي؟',
      'faq_a4': 'نعم! اذهب إلى حسابك، ثم "سيارتي" لإضافة وتتبع سجل الصيانة الخاص بك.',
      'faq_q5': 'كيف أجد قطع الغيار؟',
      'faq_a5': 'قم بزيارة علامة التبويب "قطع الغيار" لتصفح أو البحث عن قطع معينة.',
      'faq_q6': 'كيف أعيد تعيين كلمة المرور الخاصة بي؟',
      'faq_a6': 'في شاشة تسجيل الدخول، اضغط على "هل نسيت كلمة المرور؟" لاستلام رابط الاستعادة.',
      'faq_q7': 'أين يمكنني إيجاد مراكز صيانة قريبة مني؟',
      'faq_a7': 'اذهب للشاشة الرئيسية واضغط على "الأماكن القريبة" لرؤية خريطة مراكز الصيانة.',
      'faq_q8': 'كيف أفعل الوضع الليلي؟',
      'faq_a8': 'انتقل إلى الإعدادات من حسابك وقم بتفعيل مفتاح الوضع الليلي.',
      'faq_q9': 'ما هو مساعد الذكاء الاصطناعي؟',
      'faq_a9': 'مساعد الذكاء الاصطناعي هو مساعدك الافتراضي. اضغط على الأيقونة العائمة لطرح الأسئلة.',
      'faq_q10': 'كيف أغير معلومات حسابي؟',
      'faq_a10': 'اذهب إلى صفحة حسابك واضغط على "تعديل المعلومات".',

      // ================= Payments Screen =================
      'payments': 'المدفوعات',
      'manage_payments': 'إدارة المدفوعات',
      'payment_methods': 'طرق الدفع',
      'history': 'السجل',
      'add_payment_method': 'إضافة طريقة دفع',
      'default_method': 'الافتراضي',
      'select_payment_method': 'اختر طريقة الدفع',
      'credit_debit_card': 'بطاقة ائتمان / خصم',
      'add_card': 'إضافة بطاقة',
      'add_instapay': 'إضافة إنستاباي',
      'add_vodafone_cash': 'إضافة فودافون كاش',
      'card_number': 'رقم البطاقة',
      'cardholder_name': 'اسم صاحب البطاقة',
      'expiry_date': 'تاريخ الانتهاء',
      'cvv': 'الرقم السري (CVV)',
      'name': 'الاسم',
      'completed': 'مكتمل',
      'pending': 'قيد الانتظار',
    }
  };

  static String tr(BuildContext context, String key) {
    Locale locale = Localizations.localeOf(context);
    return _translations[locale.languageCode]?[key] ?? key;
  }
}